#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

Track:
    resource: '../src/Track/Infrastructure/Resources/routes'
    type: directory
